### PR TITLE
Fixes TurnerSoftware/Pingalot#6 & Bump to .NET 6

### PR DESCRIPTION
**Pull request by DanielSpindler83**
Hi @Turnerj ,
Firstly great tool and thanks for sharing.
Please let me know your feedback. Any constructive criticism is most welcome.
I am fairly new to C# and programming. I have done a lot of scripting, however I struggle with the OOP part a bit - still feeling my way around some of the design concepts and patterns. 
I was looking to use your tool and did not like the memory blow out for continuous ping.

PR related to https://github.com/TurnerSoftware/Pingalot/issues/6

I have bumped to .NET 6.
I reworked the pingsession.cs to be stateful - its now called pingstats.cs - it is only passed a single ping request.
Removed the need for a list of PingRequests.
Moved the PingRequestExportModel class into Pingalot.Core
Added Export File to the PingRequestOptions - maybe not the best idea but was the easiest to get the file details passed through to the PingRequestAgent.
Added the File Export function into PingRequestAgent  - export a record at a time as it occurs.
Catered for an error with the export file path  - if error then create file local to the exe with a generic name plus datetime.
Added a final ping stats method to pingstats to just pass in the end time.
The memory is now constant for the life of the program as we don't keep a list of ping requests.

I will be conducting further testing and would like to add some unit tests and help with some of the other issues.
I like the idea of adding MTR functionality - I was thinking of trying to replicate most of the Ping Plotter functionality but maybe in a web interface. Would be a nice challenge and your code is a great base.

Thanks,

Daniel

### CODE REVIEW

**Comment by Turnerj** [comment]
Hey @DanielSpindler83 - firstly thanks for contributing to this project! I know the project looks a little neglected, at least compared to my others, but I really appreciate you helping out.

I don't want to discourage you as generally speaking I agree with your changes however to make my life a little easier (and make any feedback easier to follow), I propose we do this in stages across a few PRs:

- .NET 6 + CI
- Unit tests (to bring parity to existing features)
- Changes for #6
- etc

Then we keep it generally to a feature per PR or a core fix per PR. Ideally, if we get it in that order, then I can generally merge them in and you can then more easily build upon the changes.

With regards to CI specifically, what might help is having a look at what I've done for a few of my other projects. I tend to have these files configured in a way that makes certain things pretty nice.

- GitHub workflow: https://github.com/TurnerSoftware/CacheTower/blob/main/.github/workflows/build.yml
- Directory.Build.props: https://github.com/TurnerSoftware/CacheTower/blob/main/src/Directory.Build.props
- (Library).csproj: https://github.com/TurnerSoftware/CacheTower/blob/main/src/CacheTower/CacheTower.csproj

A lot of each should be able to be copied into this project, allowing me to have a common base between my repositories. Happy to dig into more specifics about this in a separate PR.

One thing I do need to do (to keep it aligned with my other repositories) is change the default branch from `master` to `main`. I won't do that yet (as it will likely mess with your local repo and pull changes) but just an FYI for the future.

**Comment by Turnerj** [comment]
>  I am fairly new to C# and programming. I have done a lot of scripting, however I struggle with the OOP part a bit - still feeling my way around some of the design concepts and patterns.

I forgot to highlight this before - that's awesome you're getting into C# and programming. I hope through this project, and others, that you grow and learn through tinkering on them etc. With any PRs you raise with Pingalot (or any of my other projects), I'll work with you to make sure we have a great solution. 🙂

**Comment by DanielSpindler83** [comment]
Thanks @Turnerj , I am a big believer in doing things properly and I did make some boo boos with my branching and the PR style. I also wasnt working with a local git copy as I worked through my changes - which I appreciate was not ideal.
I am happy to start again and remove this PR. Rename your master to main and ill redo my forked repo and submit the first PR for bump to .NET 6. I will go back over all my changes and commit it in a logical order on a specific branch for issue #6 .
I use git day to day but not github, so i'm a bit unsure of the whole linked repos style and how PRs work here in GitHub and linking to issues so I got a bit lost there.
I have worked with unit tests a little bit before but im not really sure what specific tests we need(but i guess if i start I might work it out), maybe if you throw a bone and point in the right direction I can go from there? I really do want to learn more about unit testing and this is a good opportunity as I now have a pretty good understanding of the Pingalot code base. Do you use a specific unit testing framework in your other projects(I will go and have a look).

On another note, do you recommend any specific C# training or learning material - paid or unpaid?
I started learning from Pluralsight on a free VS subscription deal with work. It was pretty good. But I am looking for something a bit more intermediate and challenging. I'm guessing getting hands on with OSS is probably my best bet...

Let me know - thanks.

**Comment by Turnerj** [comment]
Hey @DanielSpindler83 - I've updated the branch name to `main`. While I don't know what you need to do on your fork to synchronise that across, these are the commands that GitHub suggests to change if your `origin` is set to this repo:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

> I use git day to day but not github, so i'm a bit unsure of the whole linked repos style and how PRs work here in GitHub and linking to issues so I got a bit lost there.

My best explanation for forks is that is just a clone of a repo but it is stored on GitHub with some extra metadata pointing back to the repo you cloned it from. I don't have a specific branching strategy for PRs to come in unlike some projects - just give the branch a name that roughly resembles the change. I don't try and muck around with what branches changes go to like having a develop branch etc - everything merges to the main branch.

With providing PRs etc, while I haven't included it in this repo, you might find a "contributing readme" in one of my other projects useful: https://github.com/TurnerSoftware/CacheTower/blob/main/CONTRIBUTING.md
I made it as a "choose your own adventure" style and pretty much covers my thoughts for any of my projects.

> I have worked with unit tests a little bit before but im not really sure what specific tests we need(but i guess if i start I might work it out), maybe if you throw a bone and point in the right direction I can go from there?

Yeah, currently with no tests in the codebase it can be a bit hard to start. Basically there are two levels of tests here that I see:
- Tests that ensure we don't break the CLI structure in the `Pingalot` assembly (these are kinda integration tests)
- Tests that ensure our `Pingalot.Core` does what it is meant to (these would be more typical unit tests)

At this stage, I'm not overly concerned about the former but the latter would be useful to try and test. To test our core logic, we probably need a way to mock the `Ping` instance that is within `PingRequestAgent`. There is a great library called Moq that I've used before _however_ the code will need to be refactored to support a custom `Ping` instance. What I'm thinking is that we'll need to wrap `Ping` ourselves in a type - potentially a factory pattern - so we can mock that. All of this though is gonna be kinda messy so may not be the first thing to test.

One good place to start though would be when you have a PR up for your PingStats changes is testing that it does what we expect. If we pass in ping results of different states, do the statistics add up correctly. Some of your changes regarding file exporting would be good to test.

> I really do want to learn more about unit testing and this is a good opportunity as I now have a pretty good understanding of the Pingalot code base. Do you use a specific unit testing framework in your other projects(I will go and have a look).

I primarily use MSTest/VSTest - this is a fairly basic testing framework for .NET but I use it for all my projects currently. I am considering switching to FluentAssertions which could mean switching to XUnit but that would be at a later date.

In the meantime, check out:
- https://github.com/Moq/moq (the type mocking framework I like to use)
- https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-mstest#create-the-first-test (MSTest)

> On another note, do you recommend any specific C# training or learning material - paid or unpaid?
> I started learning from Pluralsight on a free VS subscription deal with work. It was pretty good. But I am looking for something a bit more intermediate and challenging. I'm guessing getting hands on with OSS is probably my best bet...

I don't really have anything to overly recommend I'm afraid. It really depends on your learning style what is best etc. Like for me, I always tinkered with things and kinda randomly learnt things as I went.

I have some intermediate-to-advanced stuff in a few blog posts but they won't really touch much on what is useful here:
- https://turnerj.com/blog/levenshtein-distance-part-2-gotta-go-fast
- https://turnerj.com/blog/levenshtein-distance-part-3-optimize-everything

I also have a video on the same subject: https://www.youtube.com/watch?v=JiOYajl2Mds

**Comment by Turnerj** [comment]
So I just found that I had uncommitted changes from a while back which might trample a bit on some of your changes. I'll get my stuff up shortly and then do an initial setup of CI and a blank test project for you to integrate your changes into.

**Comment by Turnerj** [comment]
I had a look at my code - it was in rough shape as I was half way through a refactor of the layout/rendering system. I've ditched that code but synchronised some basic CI and other repo goodies from another library of mine. You should be able to start opening individual pull requests for different things (like upgrading the projects and CI to .NET 6 etc) now.

**Pull request closed without merging**
